### GET ALL PRODUCTS
GET http://127.0.0.1:3000/api/products
Content-Type: application/json


### GET PRODUCT BY ID
GET http://127.0.0.1:3000/api/products/1
Content-Type: application/json


### CREATE A NEW PRODUCT
POST http://127.0.0.1:3000/api/products
Content-Type: application/json

{
    "id": "3",
    "name": "Pencil",
    "category": "office supplies",
    "price": 1.5
}