### GET ALL PRODUCTS
GET http://127.0.0.1:3000/api/products
Content-Type: application/json


### GET PRODUCT BY ID
GET http://127.0.0.1:3000/api/products/652203c1ff2de083265c68c4
Content-Type: application/json


### CREATE A NEW PRODUCT
POST http://127.0.0.1:3000/api/products
Content-Type: application/json

{
    "name": "Produto Novo Refactoring",
    "category": "desconhecido",
    "price": 300
}

### UPDATE BY ID
PUT http://127.0.0.1:3000/api/products/651dec152893c9ab940da75a
Content-Type: application/json

{
    "name": "Classe",
    "category": "updated 2",
    "price": 3.2
}


### REMOVE BY ID
DELETE http://127.0.0.1:3000/api/products/651dec152893c9ab940da75a
Content-Type: application/json